### PR TITLE
Fixed crash when folders contain msbuild-style projects.

### PR DESCRIPTION
**Pull request by sharpninja**
Rebased as requested.

### CODE REVIEW

**Comment by TAGC** [comment]
Cheers mate.

I'd prefer for now if it handled msbuild style projects in the following way:

- Gracefully fails with `ExitFailure` if you're trying to update a specific project, and that project happens to be msbuild-style.
- Skips msbuild-style projects when running the program in recursive mode in a directory tree containing several projects, some of which may be msbuild-style.

I've added failing integration tests in the commit I pushed to your develop branch. I'd appreciate if you did the following:

- Replace `ExampleMsBuildStyleCsprojFile` with the contents of a minimal msbuild-style csproj file, since I presume you have one on hand that prompted you to open this PR.
- Update the program logic so those two integration tests pass.

I noticed that the build succeeded even though my integration tests failed, so I'll be pushing some changes to this repo's develop branch to fix my AppVeyor config so they fail. ~~You'll need to rebase on those changes.~~ (Edit) I've done this, no worries.

**Comment by sharpninja** [comment]
It would make sense to go ahead and extend functionality to including updating AssemblyInfo.cs and .nuspec files.

**Comment by TAGC** [comment]
I guess, but that would require more work. Going down that route, I'd first like to make dotnet-setversion gracefully fail for (or skip) old-style projects, release that as v2.0.1, then after that functionality to bump versions in other types of files could be implemented as a minor-level release.

**Comment by TAGC** [comment]
I'm going to close this for now, but let me know if you want it re-opened.

**Pull request closed without merging**
